### ISSUE TITLE
Unable to refresh google oauth2 token after update python social auth to 0.2.1

### ISSUE THREAD

**Issue by yaniv14** [omab/python-social-auth#485]
Using Python social auth in django project and everything was working fine.

I have just updated python social auth to 0.2.1 and I am getting error with load_strategy when trying to refresh google oauth2 token.

Until now I was using:

    strategy = load_strategy(backend='google-oauth2')
    user = UserSocialAuth.objects.get(uid=..., provider="google-oauth2")
    refresh_token(strategy=strategy, redirect_uri='http://.....')
Now I am getting this error:

    TypeError: load_strategy() got an unexpected keyword argument 'backend'

Any kind of help will be appreciated.

**Comment by omab** [comment]
It should be invoked like this:

```python
from social.apps.django_app.utils import load_strategy

user = User.objects.get(pk=...)
social = user.social_auth.get(provider='google-oauth2')
social.refresh_token(load_strategy())
```
