### ISSUE TITLE
python-social-auth currently doesn't work with Django 1.8

### ISSUE THREAD

**Issue by bogdan-kulynych** [omab/python-social-auth#668]
Error `module object has no attribute 'get_template_from_string'` occurs in [`render_html` in `DjangoTemplateStrategy`](https://github.com/omab/python-social-auth/blob/master/social/strategies/django_strategy.py#L21) and [`render_template` in `DjangoStrategy`](https://github.com/omab/python-social-auth/blob/master/social/strategies/django_strategy.py#L89), because `get_template_from_string` was removed in Django 1.8.

Django docs [recommend](https://docs.djangoproject.com/en/1.8/ref/templates/upgrading/#get-template-from-string) changing `get_template_from_string` calls to other alternatives:

> Private API get_template_from_string(template_code) was removed in Django 1.8 because it had no way to choose an engine to compile the template.
> 
> Three alternatives are available.
> 
> If you control the project’s setting, you can use one of the configured engines:
> 
> ```
> from django.template import engines
> 
> template = engines['django'].from_string(template_code)
> ```
> 
> This returns a backend-dependent Template object.
> 
> For trivial templates that don’t need context processors nor anything else, you can create a bare-bones engine and use its from_string() method:
> 
> ```
> from django.template import Engine
> 
> template = Engine().from_string(template_code)
> ```
> 
> This returns a django.template.Template because Engine is part of the Django template language’s APIs. The multiple template engines machinery isn’t involved here.
> 
> Finally, if you have access to the current context, you can use the same trick as above:
> 
> ```
> template = context.template.engine.from_string(template_code)
> ```

**Comment by sethlivingston** [comment]
+1

**Comment by omab** [comment]
A fix for this was already merged.
