### ISSUE TITLE
Make Migrations Backward-Compatible with South

### ISSUE THREAD

**Issue by clintonb** [omab/python-social-auth#353]
Using the latest commit (d53529b57f0a4992889ad490e5314a2244155afa) with Django 1.6, I get an error when running migrations introduced by #318:

```
south.exceptions.UnknownMigration: Migration 'default:0001_initial' probably doesn't exist.
Traceback (most recent call last):
  File "/Users/clintonb/.virtualenvs/edx-analytics-dashboard/lib/python2.7/site-packages/south/migration/base.py", line 302, in migration
    migration = __import__(full_name, {}, {}, ['Migration'])
  File "/Users/clintonb/.virtualenvs/edx-analytics-dashboard/src/python-social-auth/social/apps/django_app/default/migrations/0001_initial.py", line 4, in <module>
    from django.db import models, migrations
ImportError: cannot import name migrations
```

The migrations should support both Django 1.7 and South for Django < 1.7. See http://south.readthedocs.org/en/latest/releasenotes/1.0.html#library-migration-path.
